version: '3.8'

services:
  # ---------------------------------------------------------------------------
  # Database Service (PostgreSQL)
  # ---------------------------------------------------------------------------
  db:
    image: postgres:15-alpine
    container_name: silverstar-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-silverstar}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ---------------------------------------------------------------------------
  # Cache & Message Broker (Redis)
  # ---------------------------------------------------------------------------
  redis:
    image: redis:7-alpine
    container_name: silverstar-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  # ---------------------------------------------------------------------------
  # Vector Database (ChromaDB) - For RAG Engine
  # ---------------------------------------------------------------------------
  vector-db:
    image: chromadb/chroma:latest
    container_name: silverstar-vector-db
    ports:
      - "8001:8000"
    volumes:
      - chroma_data:/chroma/.chroma/index
    environment:
      - IS_PERSISTENT=TRUE

  # ---------------------------------------------------------------------------
  # Object Storage (MinIO) - S3 Compatible (Optional for Doc Storage)
  # ---------------------------------------------------------------------------
  minio:
    image: minio/minio
    container_name: silverstar-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  # ---------------------------------------------------------------------------
  # Backend API (FastAPI)
  # ---------------------------------------------------------------------------
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: silverstar-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-silverstar}
      REDIS_URL: redis://redis:6379/0
      VECTOR_DB_URL: http://vector-db:8000
      MINIO_ENDPOINT: minio:9000
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      vector-db:
        condition: service_started
    develop:
      watch:
        - action: sync
          path: ./backend/src
          target: /app/src
        - action: rebuild
          path: ./backend/pyproject.toml

  # ---------------------------------------------------------------------------
  # Background Worker (Celery/RQ)
  # ---------------------------------------------------------------------------
  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: silverstar-worker
    command: celery -A app.worker worker --loglevel=info
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-silverstar}
      REDIS_URL: redis://redis:6379/0
    depends_on:
      backend:
        condition: service_started
      redis:
        condition: service_healthy

  # ---------------------------------------------------------------------------
  # Frontend (React + Vite)
  # ---------------------------------------------------------------------------
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: silverstar-frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - backend
    develop:
      watch:
        - action: sync
          path: ./frontend/src
          target: /app/src
        - action: rebuild
          path: ./frontend/package.json

volumes:
  postgres_data:
  redis_data:
  chroma_data:
  minio_data:
